### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by louh** [BadIdeaFactory/overengineered-diplomacy#12]
I _think_ this is doable.

## Back end

- Node.js / Express server hosted via AWS or Azure
- Websocket and Redis pub/sub system for real time server-client communication
- Blockchain action log
- PostgreSQL database

## Front end // UI

- React / Redux client side single-page application (with Babel)
- Asset bundling via Webpack
- Testing / code correctness via Jest / Typescript
- Game map created from real-world boundaries in GIS, cached as map tiles at various resolutions
- Tangram for WebGL-based rendering and animation (Leaflet base)
- Period-influenced (1920s?) in-game artwork and UI

## Absolutely necessary features

- Character creation system
- User accounts
- Animation (water, turns)

**Comment by slifty** [comment]
This is an excellent list; I would like us to eventually consider adding map animations for the UI -- both in terms of having the water look like it moves but also animating turns -- to the Absolutely necessary features.

**Comment by louh** [comment]
Yes and yes. Added!

**Comment by louh** [comment]
I've ported most of these things to the Projects system.
